language: go
go:
  - 1.9.x
  - 1.10.x
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - ./.test-coverage travis-ci
  - ./.test-testfiles
  - ./.travis.gofmt.sh
  - find . -type f -name '*.go' | grep -v '^./vendor/' | xargs misspell -error
  - go install github.com/FreifunkBremen/yanic
